version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: rindwa-postgres
    environment:
      POSTGRES_DB: rindwa_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: rindwa-backend
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/rindwa_db
      JWT_SECRET: your-super-secret-jwt-key-change-this-in-production
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    restart: unless-stopped

  admin-dashboard:
    build: ./admin-dashboard
    container_name: rindwa-admin
    ports:
      - "3001:80"
    depends_on:
      - backend
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: rindwa-frontend
    ports:
      - "3002:80"
    depends_on:
      - backend
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: rindwa-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - admin-dashboard
      - frontend
    restart: unless-stopped

volumes:
  postgres_data: 