// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://upanabvcqggezilbhgbn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVwYW5hYnZjcWdnZXppbGJoZ2JuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNTQ2NTMsImV4cCI6MjA2NTgzMDY1M30.udYTSrZXGFTZkns0NceUWvV6BSiXmfr_pecCBQTr3Ok";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);